- name: Deploy VM "{{ vm_name }}" on "{{ vcenter_hostname }}" - "{{ cl_name }}"
  args:
    warn: false
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: False
    name: "{{ vm_name }}"
    template: TEMPLATE_RHEL84_x86_ATUAL
    datacenter: "{{ dc_name }}"
    folder: VM
    cluster: "{{ cl_name }}"
    datastore: "{{ ds_name }}"
    networks:
    - name: "{{ net_name }}"
      ip: "{{ vm_ip }}"
      netmask: 255.255.255.0
      gateway: "{{ vm_gw }}"
      type: static
      dns_servers: 192.168.0.1
      start_connected: yes
    customization:
      hostname: "{{ vm_name }}"
      domain: intra.domain.com.br
      dns_suffix:
      - intra.domain.com.br
      - sede.domain.com.br
      - domain.com.br
      dns_servers:
      - 192.168.0.1
      - 192.168.0.2
      - 192.168.0.3
    state: poweredon
    wait_for_ip_address: yes
  delegate_to: localhost

- name: The vm "{{ vm_name }}" is accessible via ssh - "{{ vm_ip }}"
  shell: ping -c4 "{{ vm_ip }}"
  register: ping

- name: Check ping
  debug:
    msg: "{{ ping.stdout_lines }}"
